### ISSUE TITLE
Scroll-blocking touchstart event

### ISSUE THREAD

**Issue by ParogDev** [szboynono/mosha-vue-toastify#17]
Any time I use a toast, I get this warning in the console;

```[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952```

Would it be possible to put the event as passive so this can be used in production? :)

**Comment by ParogDev** [comment]
The issue only seems to be on chrome; Firefox does not display any warning.

**Comment by szboynono** [comment]
Good catch and thanks for the feedback! I made a little fix, can you try v1.0.21 ?

**Comment by ParogDev** [comment]
v1.0.21 fixes it. Your reply was so fast that I came back to my work machine to give you an answer in a reasonable time myself.

Amazing work by the way. Thank you for the typescript types!
