### ISSUE TITLE
Toasts overlap each other when done in a 'for'-ish type loop

### ISSUE THREAD

**Issue by nisenihonjin** [szboynono/mosha-vue-toastify#19]
When doing a 'for'-ish loop (for, forEach, etc.) through an AJAX's response errors and making a toast for each one, they overlap each other on the screen instead of cascading below each other. A temporary workaround I've found is to wrap the `createToast` function in a `setTimeout` of only 1 millisecond, but a permanent fix within the library would be much appreciated.

**Comment by szboynono** [comment]
hi! Thanks for the feedback! Good catch, by the way, I made a little fix for it. Can you try out v1.0.22?

**Comment by szboynono** [comment]
Hi! Thanks for your feedback! I made a little update to the code. Can you try out v1.0,23?

**Comment by nisenihonjin** [comment]
Thanks! Looks good!
