### ISSUE TITLE
Render as HTML

### ISSUE THREAD

**Issue by jrbautista10** [szboynono/mosha-vue-toastify#6]
Able to use it easily! Great package!

How can I render the description as HTML?
![image](https://user-images.githubusercontent.com/37645059/125172970-263e9100-e1ef-11eb-8d00-bae25cc885e4.png)

**Comment by szboynono** [comment]
Hi! Thanks for the feedback, I added the html parsing for the description property in version 1.0.14.
You can look into passing a custom component into the content if you need more customization : D.
