### ISSUE TITLE
Migrate to React project?

### ISSUE THREAD

**Issue by fewwwww** [szboynono/mosha-vue-toastify#9]
Have tried it on Vue project and LOVE it! 
Any possibility to use it in React project or any plan to migrate it to React?

**Comment by fewwwww** [comment]
I haven't work with open source on npm packages, but I can help building the react version if you allow.

**Comment by szboynono** [comment]
Glad you like it! oh yeah, I've actually started the react version of this. If you want to use it now, there are so many great libraries out there as well e.g react-toastify.
